name: scicat-workshop-prep

channels:
  - defaults
  - conda-forge

dependencies:
  - asttokens=2.0.5
  - webencodings=0.5.1
  - pexpect=4.8.0
  - libgomp=11.2.0
  - mkl_random=1.2.2
  - pysocks=1.7.1
  - prompt-toolkit=3.0.36
  - backcall=0.2.0
  - tomli=2.0.1
  - terminado=0.17.1
  - numpy=1.23.5
  - bcrypt=3.2.0
  - notebook=6.5.2
  - typing-extensions=4.4.0
  - tinycss2=1.2.1
  - mkl-service=2.4.0
  - pure_eval=0.2.2
  - libffi=3.4.2
  - _libgcc_mutex=0.1
  - stack_data=0.2.0
  - pytz=2022.7
  - tornado=6.2
  - dataclasses=0.8
  - ptyprocess=0.7.0
  - traitlets=5.7.1
  - libgfortran5=11.2.0
  - pynacl=1.5.0
  - tzdata=2022g
  - entrypoints=0.4
  - babel=2.11.0
  - pip=22.3.1
  - libsodium=1.0.18
  - argon2-cffi-bindings=21.2.0
  - sniffio=1.2.0
  - nest-asyncio=1.5.6
  - invoke=1.6.0
  - jupyterlab=3.5.3
  - libgfortran-ng=11.2.0
  - flit-core=3.6.0
  - attrs=22.1.0
  - numpy-base=1.23.5
  - json5=0.9.6
  - h5py=3.7.0
  - nbformat=5.7.0
  - email-validator=1.3.1
  - zeromq=4.3.4
  - nbclient=0.5.13
  - openssl=1.1.1t
  - jupyterlab_server=2.19.0
  - bleach=4.1.0
  - defusedxml=0.7.1
  - idna=3.4
  - setuptools=65.6.3
  - cffi=1.15.1
  - jupyter_core=5.2.0
  - matplotlib-inline=0.1.6
  - dnspython=2.3.0
  - mkl_fft=1.3.1
  - brotlipy=0.7.0
  - beautifulsoup4=4.11.1
  - xz=5.2.10
  - sqlite=3.40.1
  - ipython_genutils=0.2.0
  - intel-openmp=2021.4.0
  - psutil=5.9.0
  - requests=2.28.1
  - platformdirs=2.5.2
  - six=1.16.0
  - wcwidth=0.2.5
  - urllib3=1.26.14
  - pycparser=2.21
  - ipykernel=6.19.2
  - nbconvert=6.5.4
  - icu=58.2
  - lxml=4.9.1
  - nbclassic=0.5.2
  - notebook-shim=0.2.2
  - decorator=5.1.1
  - pygments=2.11.2
  - debugpy=1.5.1
  - charset-normalizer=2.0.4
  - pandoc=2.12
  - pyzmq=23.2.0
  - argon2-cffi=21.3.0
  - libxslt=1.1.35
  - zlib=1.2.13
  - ncurses=6.4
  - blas=1.0
  - tk=8.6.12
  - hdf5=1.10.6
  - libxml2=2.9.14
  - cryptography=38.0.4
  - jinja2=3.1.2
  - python-dateutil=2.8.2
  - mistune=0.8.4
  - jedi=0.18.1
  - bzip2=1.0.8
  - jupyterlab_pygments=0.1.2
  - ca-certificates=2022.12.7
  - mkl=2021.4.0
  - readline=8.2
  - libgcc-ng=11.2.0
  - jupyter_client=7.4.9
  - markupsafe=2.1.1
  - packaging=22.0
  - send2trash=1.8.0
  - paramiko=2.8.1
  - prometheus_client=0.14.1
  - pyopenssl=22.0.0
  - soupsieve=2.3.2.post1
  - python-fastjsonschema=2.16.2
  - anyio=3.5.0
  - jupyter_server=1.23.4
  - python=3.10.9
  - scitacean=23.1.1
  - typing_extensions=4.4.0
  - wheel=0.38.4
  - jsonschema=4.17.3
  - ipython=8.10.0
  - pyrsistent=0.18.0
  - ld_impl_linux-64=2.38
  - websocket-client=0.58.0
  - _openmp_mutex=5.1
  - comm=0.1.2
  - pandocfilters=1.5.0
  - fabric=2.6.0
  - pickleshare=0.7.5
  - libuuid=1.41.5
  - parso=0.8.3
  - certifi=2022.12.7
  - executing=0.8.3
  - libstdcxx-ng=11.2.0

